version: '3'
services:
  nginx:
    env_file:
      - .env
    image: nginx:latest
    ports:
      - "${DEV_NGINX_PORT}:80"
    volumes:
       - ./wordpress:/opt/wordpress
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    env_file:
      - .env
    build:
      context: .
    volumes:
       - ./wordpress:/opt/wordpress
       - ./npm_cache:/root/.npm/_cacache
    links:
      - db
  db:
    env_file:
      - .env  
    image: mysql:5.7
    ports:
      - "${DEV_MYSQL_PORT}:3306"
    volumes:
      - ${DEV_MYSQL_DATA_DIR}:/var/lib/mysql