version: '3'
services:
  wordpress_phpunit:
    image: "chriszarate/wordpress-phpunit"
    volumes:
       - ./wordpress:/opt/wordpress
       - "testsuite:/tmp"
       - ./install-wp-tests.sh:/app/bin/install-wp-tests.sh
    links:
      - db-unit
  db-unit:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "wordpress_test"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
volumes:
  testsuite: {}