name: Lint the PHP
on: [pull_request]

jobs:
    lint-php:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@2.9.0
              with:
                  php-version: 7.3
            - name: Lint the PHP
              run: bin/phpcs.sh
              shell: bash
