name: Lint and test JS
on: [pull_request]

jobs:
    test-lint-js:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '14'
            - name: Lint and test the JS
              run: bin/js_lint_test.sh
              shell: bash
